{% set name = "olefile" %}
{% set version = "0.44" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 61f2ca0cd0aa77279eb943c07f607438edf374096b66332fae1ee64a6f0f73ad

build:
    number: 0
    script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - olefile

about:
  home: http://www.decalage.info/python/olefileio
  license:  BSD 2-Clause
  license_family: BSD
  summary: >
    Python package to parse, read and write Microsoft OLE2 files
    (Structured Storage or Compound Document, Microsoft Office) -
    Improved version of the OleFileIO module from PIL, the Python
    Image Library.
  dev_url: https://bitbucket.org/decalage/olefileio_pl/src

extra:
  recipe-maintainers:
    - dgursoy
    - decarlof
    - ericdill
    - licode
    - ravescovi
    - tacaswell
    - ocefpaf
