{% set name = "olefile" %}
{% set version = "0.42.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.zip
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 8a3226dba11349b51a2c6de6af0c889324201f14a8c30992b7877109090e36e0

build:
    number: 1
    script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - olefile

about:
  home: http://www.decalage.info/python/olefileio
  license:  BSD License 2-Clause
  license_family: BSD
  summary: >
      Python package to parse, read and write Microsoft OLE2 files 
      (Structured Storage or Compound Document, Microsoft Office) - 
      Improved version of the OleFileIO module from PIL, the Python 
      Image Library.
  dev_url: https://bitbucket.org/decalage/olefileio_pl/src

extra:
    recipe-maintainers:
        - dgursoy
        - decarlof
        - ericdill
        - licode
        - ravescovi
        - tacaswell
