travis:
  secure:
    BINSTAR_TOKEN: LBIkGY7QlD8wNlKcWWJkqJs14SBpspACEkZg808nlox8RBgI7l8BFJGB9r/CaWXlzxvH6MMRssNA+u3tkwzWzN4Mo9EAB7GxgRqx6kT/MyOF9XpmHMXeb5IBmi5tMQ95dpg+cUqrAHlEpk7qI8MRTFMvX35nXWbp7W9vZyLadvYAPLYr/g3q+ik88K+7PxOFk8pZSpAS6IKwxFxrdiVIFiSXEiaYVv8G2du+myVHX95XQw5vL27EcedHyPSOhFQd6fLdWsKGQWBnciRi0I4Iye5FX6aWaVE5nSupcvyS/RqdOq9bco890TrN+iz71CzYYzU20+9L0si7G9WgvGuA9BW5k99eS2E9i2v3MWyNgpjOZPqRhNUzQEM8+aFjpnChbpmUGvT5P2P5JsMOR8g/Fmp3B8sBbKohn0Li7clMTxWOgsIuaBrYRcHO2mDScigMMch7YOxjHLcutLEe+deKOKlYXCAIrbOAtos9se2ya+EDrICO/0SQwN6TPeHiRQax0T14cLzN1ZkbdC/3jQHnIHc33kgQFay/rI+WD35Y25isUVDNP/EpyqJh2wMN/ufw6fHAQDlbrk5CtMKCxc8U8ybyxYnwnlca3XJPUpgp+NW6ZYv9096yi+EhZppdGZAgxEZ4bkgzwBsxugmPJqATUJCoaneeVOl2Xl4NhKQyP1M=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
