travis:
  secure:
    BINSTAR_TOKEN: hyo8qb9cF4A44xT0y5BjdrED7d/9auw/699FjvoaB0zRS+DpcOiIf3vePo/VODU4B4RTUyrm3wG9khimDg1vPvRZku2zSmLmoE89C62Fn13h9IBzIdcjA+iKU0lAIpe9pqIqOliAlxkE+ySQ172P5tkshzGiL0TWzthifezsVx8oQyCpWu2ueUABZkJ17tCiqDdd2TSlQc3PHZfgKHLKTNj/W/Lr/4V8z1pN37iIjFRU4B7NhbP5toa/pZdsKaB0Gc8R9k6j83TYyigV52YlEDNffws7Q4R+TMW0vuK0XwrC1TGfNEASyemb7y42dXwJQ1iJZ8qh2BUmWTCB9TsNfVYiTtMRQdJ1rdGQ/+yS8R8Ayboo1eCSNVMVLOCtdMvl6MHSnNDW6Rls8suxKyBHDWi9mzpHWopiBFirOH/XH1xMPsDAWiLpTnxalYKcyHwuF/fneXvppc6vZ8XeC/qL1Wo9bhCV8Qpld+O+OkYb1Qp6H4vpOos17SnbjYR0+0jprDKLazvhyB5TL/G6jNyKhP6h2MNhPy6VyG7oUdI+C2uo2JMQAI+ZhTUTKaaNDuoDDSYK+TM49lBng0Duj48ZPGJJyHivDYjz4k9g+M70HRIbXxn3CtTA9D+YSferPnyjWK1IqXB9Vom5Bltjiqn0wwl/qfFTQLlECkJNIn7U1V4=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
